#autor: Borgiliel
import sys
import time

a=2
b=0.2
c=0.08


def intro():
    time.sleep(a)
    s = '   *BLÉM. BLÉM. BLÉM*'
    for character in s:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    print()
    print()
    time.sleep(a)
    print('O sino da Igreja em ruínas toca na superfície, e te desperta. ')
    time.sleep(a)
    print('É um chamado demoníaco, a forma de comunicação entre as horrendas criaturas que dominaram o planeta Terra.')
    time.sleep(a)
    print()
    time.sleep(a)
    print('Você não se move.')
    time.sleep(a)
    print('Você está nos esgotos de Carmville, cidade em que nasceu. ')
    time.sleep(a)
    print('Dois anos atrás, o Apocalipse iniciou, e a humanidade travou uma grande batalha contra dos demônios que desceram dos céus vermelhos, em chamas. ')
    time.sleep(a)
    time.sleep(a)
    print('Todo o poder bélico disponível foi massacrado como insetos pelos enxames de diabretes, pelos poderosos demonarcas,',time.sleep(b),'e a humanidade dominada em poucos meses.')
    time.sleep(a)
    time.sleep(a)
    print('Os agora proprietários da Terra, os doze Senhores das Trevas que comandaram as tropas invasoras criaram campos de refugiados, para onde boa parte dos que você conhecia foram enviados.')
    time.sleep(a)
    time.sleep(a)
    print('Seus amigos. Seus pais.')
    print('')
    time.sleep(a)
    print('Os campos foram rapidamente dizimados')
    time.sleep(a)
    print()
    time.sleep(a)
    print('Por alguma razão sinistra você foi um dos poucos poupados, e, libertado no mundo com nada além de uma marcação em ferro quente com o sinal do Senhor da Trevas que domina a sua região ')
    #print('Murmur, o Abutre.')
    print()
    time.sleep(a)
    print()
    time.sleep(a)
    print()
    time.sleep(a)
    print()
    time.sleep(a)
    print('Você está perdido em seus pensamentos, quando vê um diabrete azulado, com olhos arregalados em um sinistro tom de amarelo. ')
    time.sleep(a)
    print('Ele está próximo, e vem distraidamente em sua direção. Rói o que parece ser um osso de algum animal, e chia entre os dentes pontudos de satisfação com a refeição. ')
    time.sleep(a)
    print('Não é comum diabretes virem para o subterrâneo, e esse certamente está se escondendo para comer, sem a proteção do céu infernal da superfície. ')
    print()
    time.sleep(a)
    print('Ele certamente te atacará. Você precisa fazer algo.')
    time.sleep(a)
    print('Escolha 1: Esgueirar-se nas sombras, e esperar a criatura passar.')
    time.sleep(a)
    print('Escolha 2: Atacar a criatura, usando uma pedra redonda que está ao seu lado.')
    time.sleep(a)
    print('Escolha 3: Atacar a criatura, usando a faca que carrega consigo.')
    time.sleep(a)
    print()
    primeirocaminho = input('Qual será a ação que você tomará? 1/2/3 ')
    if primeirocaminho == '1':
        print('')
        caminho1()
    elif primeirocaminho == '2':
        print('')
        caminho2()
    elif primeirocaminho =='3':
        print('')
        caminho3()

def caminho1():
    print()
    time.sleep(a)
    print('Você se esconde rapidamente, escondendo-se atrás de uma coluna do antigo metrô. ')
    time.sleep(a)
    print('A criatura se aproxima lentamente, e o tempo parece não passar.')
    time.sleep(a)
    print('Você escuta seus passos úmidos se aproximando, e não consegue, de onde está, ver a posição do seu inimigo.')
    time.sleep(a)
    print('Ele está próximo, você consegue escutar o estralar dos ossos na boca cheia de saliva.')
    time.sleep(a)
    print('O cheiro de enxofre, forte em toda a parte, é ainda mais saliente agora.')
    time.sleep(a)
    print()
    time.sleep(a)
    print('E você ouve os passos se afastando lentamente, pisando nas poças de água de forma despreocupada.')
    time.sleep(a)
    print()
    time.sleep(a)
    print('Você solta um suspiro, aliviado. Suas mãos estão suadas, e seu coração acelerado.')
    time.sleep(a)
    print()
    print('Mas para, congelado. ')
    time.sleep(a)
    time.sleep(a)
    print('Zunindo, se aproximam pela sua frente ao menos meia dúzia de demônios alados, com seus corpos gosmentos, parecendo sapos, levitando no ar. ')
    time.sleep(a)
    print('O bafo pútrido de atinge, e você ouve eles falando o idioma horrível das profundezas do inferno, e você entende o suficiente para perceber que eles perseguem o diabrete que passou por você a pouco. ')
    time.sleep(a)
    time.sleep(a)
    print('...')
    time.sleep(a)
    print('É tarde demais, você foi visto. Sibilando, a voz cruel diz o que você temia: ')
    time.sleep(a)
    y='     - yäkk läk dûm. Comida!!'
    for character in y:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(b)
    time.sleep(a)
    print()
    time.sleep(a)
    print('Você percebe que só tem duas opções: ')
    time.sleep(a)
    print('Escolha 1: Virar e correr, em direção à saída do metrô')
    time.sleep(a)
    print('Escolha 2: Atacar os demônios, usando as mãos e sua faca')
    time.sleep(a)
    escolha1 = input('O que você fará? 1/2/3?')
    if escolha1 == '1':
        print ('')
        caminho1_1()
    elif escolha1 == '2':
        print('')
        caminho1_2()


def caminho2():
    print()

def caminho3():
    print()

def caminho1_1():
    print()

def caminho1_2():
    print()

print ()
print()
#print('         #########################################')
#print('         ##	                         	##')
#print('         ##         Doom of Humanity		##')
#print('         ##	                         	##')
#print('         #########################################')
print ()
print()
print()     
print('########   #######   #######  ##     ##     #######  ########    ##     ## ##     ## ##     ##    ###    ##    ## #### ######## ##    ## ')
print('##     ## ##     ## ##     ## ###   ###    ##     ## ##          ##     ## ##     ## ###   ###   ## ##   ###   ##  ##     ##     ##  ##  ')
print('##     ## ##     ## ##     ## #### ####    ##     ## ##          ##     ## ##     ## #### ####  ##   ##  ####  ##  ##     ##      ####   ')
print('##     ## ##     ## ##     ## ## ### ##    ##     ## ######      ######### ##     ## ## ### ## ##     ## ## ## ##  ##     ##       ##    ')
print('##     ## ##     ## ##     ## ##     ##    ##     ## ##          ##     ## ##     ## ##     ## ######### ##  ####  ##     ##       ##    ')
print('##     ## ##     ## ##     ## ##     ##    ##     ## ##          ##     ## ##     ## ##     ## ##     ## ##   ###  ##     ##       ##  ')  
print('########   #######   #######  ##     ##     #######  ##          ##     ##  #######  ##     ## ##     ## ##    ## ####    ##       ##')
print()
print()
time.sleep(a)
print ()
print('O Apocalipse ocorreu. A raça humana foi derrotada na batalha final.')
time.sleep(a)
print('O mundo em ruínas é dominado por demônios, e você é um dos poucos sobreviventes.')
print()
time.sleep(a)

inicio= (input('Deseja Iniciar a aventura? (S/N): '))
if inicio == 'N' or inicio == 'n':
    print('Até a próxima, sobrevivente.')
elif inicio == 'S' or inicio == 's':
    intro()

