print ()
print()
print()
print()     
print('########   #######   #######  ##     ##     #######  ########    ##     ## ##     ## ##     ##    ###    ##    ## #### ######## ##    ## ')
print('##     ## ##     ## ##     ## ###   ###    ##     ## ##          ##     ## ##     ## ###   ###   ## ##   ###   ##  ##     ##     ##  ##  ')
print('##     ## ##     ## ##     ## #### ####    ##     ## ##          ##     ## ##     ## #### ####  ##   ##  ####  ##  ##     ##      ####   ')
print('##     ## ##     ## ##     ## ## ### ##    ##     ## ######      ######### ##     ## ## ### ## ##     ## ## ## ##  ##     ##       ##    ')
print('##     ## ##     ## ##     ## ##     ##    ##     ## ##          ##     ## ##     ## ##     ## ######### ##  ####  ##     ##       ##    ')
print('##     ## ##     ## ##     ## ##     ##    ##     ## ##          ##     ## ##     ## ##     ## ##     ## ##   ###  ##     ##       ##  ')  
print('########   #######   #######  ##     ##     #######  ##          ##     ##  #######  ##     ## ##     ## ##    ## ####    ##       ##')
print()
print ()
print()
print ()
print('O Apocalipse ocorreu. A raça humana foi derrotada na batalha final.')
print('O mundo em ruínas é dominado por demônios, e você é um dos poucos sobreviventes.')
print()

inicio= (input('Deseja Iniciar a aventura? (S/N): '))
if inicio == 'N' or inicio == 'n':
    print('Até a próxima, sobrevivente.')
elif inicio == 'S' or inicio == 's':
    print('                             *BLÉM. BLÉM. BLÉM*')
print()
print()
print('O sino da Igreja em ruínas toca na superfície, e te desperta. ')
print('É um chamado demoníaco, a forma de comunicação entre as horrendas criaturas que dominaram o planeta Terra.')
print()
print('Você não se move.')
print('Você está nos esgotos de Carmville, cidade em que nasceu. ')
print('Dois anos atrás, o Apocalipse iniciou, e a humanidade travou uma grande batalha contra dos demônios que desceram dos céus vermelhos, em chamas. ')
print('Todo o poder bélico disponível foi massacrado como insetos pelos enxames de diabretes, pelos poderosos demonarcas, e a humanidade dominada em poucos meses.')
print('Os agora proprietários da Terra, os doze Senhores das Trevas que comandaram as tropas invasoras criaram campos de refugiados, para onde boa parte dos que você conhecia foram enviados. Seus amigos. Seus pais.')
print('')
print('Os campos foram rapidamente dizimados')
print()
print('Por alguma razão sinistra você foi um dos poucos poupados, e, libertado no mundo com nada além de uma marcação em ferro quente com o sinal do Senhor da Trevas que domina a sua região: ')
print('Murmur, o Abutre.')
print()
print()
print()
print()
print('Você está perdido em seus pensamentos, quando vê um diabrete azulado, com olhos arregalados em um sinistro tom de amarelo. ')
print('Ele está próximo, e vem distraidamente em sua direção. Rói o que parece ser um osso de algum animal, e chia entre os dentes pontudos de satisfação com a refeição. ')
print('Não é comum diabretes virem para o subterrâneo, e esse certamente está se escondendo para comer, sem a proteção do céu infernal da superfície. ')
print()
print('Você está fora do campo de visão do distraído demônio. O que fará?')
print()
print('Caminho 1: Esgueirar-se nas sombras, e esperar a criatura passar.')
print('Caminho 2: Atacar a criatura, usando uma pedra redonda que está ao seu lado.')
print('Caminho 3: Atacar a criatura, usando a faca que carrega consigo.')
primeirocaminho = input ('Qual caminho você escolherá? 1/2/3? ')
if primeirocaminho == 1:
    print('')
elif primeirocaminho == 2:
    print('')
elif primeirocaminho ==3:
    print('')
